# There is the fix for the error:
  --  Collecting git+https://github.com/usalko/django-mutant.git@feature/django4 (from -r /requirements.txt (line 5))
  Cloning https://github.com/usalko/django-mutant.git (to revision feature/django4) to /tmp/pip-req-build-pd958io0
  Running command git clone --filter=blob:none --quiet https://github.com/usalko/django-mutant.git /tmp/pip-req-build-pd958io0
  Running command git checkout -b feature/django4 --track origin/feature/django4
  branch 'feature/django4' set up to track 'origin/feature/django4'.
  Switched to a new branch 'feature/django4'
  Resolved https://github.com/usalko/django-mutant.git to commit 579dc2a2ee9d47789ab5e2feae16f86486f2bdf1
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-pd958io0/setup.py", line 5, in <module>
          from mutant import __version__
        File "/tmp/pip-req-build-pd958io0/mutant/__init__.py", line 9, in <module>
          __version__ = '.'.join(VERSION)
                        ^^^^^^^^^^^^^^^^^
      TypeError: sequence item 0: expected str instance, int found
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
The command '/bin/sh -c pip install --prefix=/install --no-binary multidict,yarl -r /requirements.txt' returned a non-zero code: 1
Can't docker_build mast.eu.spb.ru/dydast:v1dev-mutant Dockerfile .